#!/usr/bin/perl
$pdflatex = 'lualatex %O %S';
$biber = 'biber --bblencoding=utf8 -u -U';
$pdf_mode = 1;
$bibtex_use = 2;
$pdf_previewer = 'okular --unique';
$clean_ext .= '%R.ltjruby %R.nav %R.snm %R.vrb';
